CREATE TABLE `geo_knowledge` (
	`id` int AUTO_INCREMENT NOT NULL,
	`locationName` varchar(255) NOT NULL,
	`locationNameAr` varchar(255),
	`country` varchar(100),
	`countryCode` varchar(10),
	`region` varchar(100),
	`city` varchar(100),
	`latitude` varchar(30),
	`longitude` varchar(30),
	`culturalContext` text,
	`architecturalStyle` text,
	`climate` varchar(100),
	`vegetation` text,
	`historicalPeriod` varchar(100),
	`colorPalette` json,
	`lightingCharacter` varchar(100),
	`atmosphericMood` varchar(100),
	`knowledgeData` json,
	`streetViewAvailable` int DEFAULT 0,
	`mapsPlaceId` varchar(255),
	`searchCount` int DEFAULT 0,
	`lastSearched` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `geo_knowledge_id` PRIMARY KEY(`id`)
);
